spring.application.name=weather-service

app.cors.allowed-origins=http://localhost:5173
server.port=8080
server.address=0.0.0.0

spring.cache.type=caffeine
# Evict after 1 hour (Met Éireann updates hourly) or when cache hits 500 locations
spring.cache.caffeine.spec=expireAfterWrite=1h,maximumSize=500